services:
  Qwen3-30B-A3B-Thinking-2507-FP8-tp4-xinference:
    image: ${IMAGE}
    container_name: Qwen3-30B-A3B-Thinking-2507-FP8-tp4-xinference
    restart: unless-stopped  # 更智能的重启策略
    shm_size: 256g
    privileged: true
    ports:
      - "${service_port}:${service_port}"
    cap_add:
      - SYS_NICE
    environment:
      - model_name=${model_name}
      - model_directory=${model_directory}
      # 稳定性关键配置
      - VLLM_ENGINE_ITERATION_TIMEOUT_S=864000 # vLLM引擎超时(24小时)
      - XINFERENCE_SSE_PING_ATTEMPTS_SECONDS=864000
      - VLLM_NO_USAGE_TIMEOUT=0               # 禁用无请求超时
      - VLLM_NO_USAGE_STATS=1
       # 显存优化（防止单实例OOM）
      - VLLM_LOGGING_LEVEL=DEBUG    
      - GPU_LIST=${GPU_LIST}                     # 用到的GPU 列表 4= tp2 *instance_nums
      - instance_nums=${instance_nums}
      - XOSCAR_CPU_AFFINITY=1
    volumes:
      - ${LLM_DATA_DIR}:/weights
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://0.0.0.0:${service_port}/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint:
      - /bin/bash
      - -c
      - |
        # 防止SIGTERM导致退出
        trap : TERM INT
        cd /test/qwen3/local

        echo "=================== start run supervisor ========================="
        xinference-local -H 0.0.0.0 -p ${service_port} &  
        until curl -s http://0.0.0.0:${service_port}/status; do
          sleep 5
        done

        # 启动模型服务
        if ! command -v xinference &> /dev/null; then
            echo "Error: xinference command not found. Please install Xinference first."
            exit 1
        fi

        # 启动两个模型副本，共享UID, 可以通过同一个UID去分发调度请求
        echo "==================== Launching Model Replica 1 ===================="

        echo '{
          "model_path": "/weights/'$${model_directory}'",
          "additional_params": {
            "tensor_parallel_size": 4,
            "max_model_len": 131072,
            "enforce_eager": true,
            "reasoning_parser": "deepseek_r1"
          }
        }' > register_qwen3.json

        python launch_qwen3_think.py --url http://127.0.0.1:${service_port} --model-config register_qwen3.json --gpu_idx $$GPU_LIST --instance-nums $$instance_nums

        # 输出汇总信息
        echo "=================================================================="
        echo "Supervisor: http://0.0.0.0:${service_port}"
        echo "Model Name: $$model_name (30B)"
        echo "Quantization: fp8"
        echo "=================================================================="

        tail -f /dev/null 
